import {
    IconAlertTriangle,
    IconArrowRight,
    IconBox,
    IconBrandGithub,
    IconBrandTwitter,
    IconCheck,
    IconChevronLeft,
    IconChevronRight,
    IconCommand,
    IconCreditCard,
    IconCrown,
    IconDeviceLaptop,
    IconDotsVertical,
    IconFile,
    IconFileText,
    IconFolder,
    IconHelpCircle,
    IconLayoutDashboard,
    IconLayoutKanban,
    IconLoader2,
    IconLogin,
    IconMoon,
    IconPalette,
    IconPhoto,
    IconPizza,
    IconPlus,
    type IconProps,
    IconSettings,
    IconStar,
    IconSun,
    IconTrash,
    IconUser,
    IconUserCircle,
    IconUserEdit,
    IconUsers,
    IconUserX,
    IconX,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
    dashboard: IconLayoutDashboard,
    logo: IconCommand,
    login: IconLogin,
    close: IconX,
    product: IconBox,
    palette: IconPalette,
    spinner: IconLoader2,
    kanban: IconLayoutKanban,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    trash: IconTrash,
    employee: IconUserX,
    post: IconFileText,
    page: IconFile,
    userPen: IconUserEdit,
    user2: IconUserCircle,
    media: IconPhoto,
    settings: IconSettings,
    billing: IconCreditCard,
    ellipsis: IconDotsVertical,
    add: IconPlus,
    warning: IconAlertTriangle,
    user: IconUser,
    arrowRight: IconArrowRight,
    help: IconHelpCircle,
    pizza: IconPizza,
    sun: IconSun,
    moon: IconMoon,
    laptop: IconDeviceLaptop,
    github: IconBrandGithub,
    twitter: IconBrandTwitter,
    check: IconCheck,
    workspace: IconFolder,
    teams: IconUsers,
    pro: IconCrown,
    exclusive: IconStar,
    account: IconUserCircle,
    profile: IconUser,
};
