import type { WorldRegion } from "@/types/geo.types";

/**
 * Reference metadata for every ISO 3166-1 country, keyed by the numeric code used by the
 * Natural Earth / world-atlas topology. Columns: numeric, alpha-2, alpha-3, English name,
 * capital, region, subregion. Generated from the `world-countries` dataset.
 */
type CountryReferenceRow = readonly [
    numeric: string,
    alpha2: string,
    alpha3: string,
    name: string,
    capital: string,
    region: WorldRegion,
    subregion: string,
];

export const COUNTRY_REFERENCE_ROWS: readonly CountryReferenceRow[] = [
    ["004", "AF", "AFG", "Afghanistan", "Kabul", "Asia", "Southern Asia"],
    ["008", "AL", "ALB", "Albania", "Tirana", "Europe", "Southeast Europe"],
    ["010", "AQ", "ATA", "Antarctica", "", "Antarctic", "Antarctic"],
    ["012", "DZ", "DZA", "Algeria", "Algiers", "Africa", "Northern Africa"],
    ["016", "AS", "ASM", "American Samoa", "Pago Pago", "Oceania", "Polynesia"],
    ["020", "AD", "AND", "Andorra", "Andorra la Vella", "Europe", "Southern Europe"],
    ["024", "AO", "AGO", "Angola", "Luanda", "Africa", "Middle Africa"],
    ["028", "AG", "ATG", "Antigua and Barbuda", "Saint John's", "Americas", "Caribbean"],
    ["031", "AZ", "AZE", "Azerbaijan", "Baku", "Asia", "Western Asia"],
    ["032", "AR", "ARG", "Argentina", "Buenos Aires", "Americas", "South America"],
    ["036", "AU", "AUS", "Australia", "Canberra", "Oceania", "Australia and New Zealand"],
    ["040", "AT", "AUT", "Austria", "Vienna", "Europe", "Central Europe"],
    ["044", "BS", "BHS", "Bahamas", "Nassau", "Americas", "Caribbean"],
    ["048", "BH", "BHR", "Bahrain", "Manama", "Asia", "Western Asia"],
    ["050", "BD", "BGD", "Bangladesh", "Dhaka", "Asia", "Southern Asia"],
    ["051", "AM", "ARM", "Armenia", "Yerevan", "Asia", "Western Asia"],
    ["052", "BB", "BRB", "Barbados", "Bridgetown", "Americas", "Caribbean"],
    ["056", "BE", "BEL", "Belgium", "Brussels", "Europe", "Western Europe"],
    ["060", "BM", "BMU", "Bermuda", "Hamilton", "Americas", "North America"],
    ["064", "BT", "BTN", "Bhutan", "Thimphu", "Asia", "Southern Asia"],
    ["068", "BO", "BOL", "Bolivia", "Sucre", "Americas", "South America"],
    ["070", "BA", "BIH", "Bosnia and Herzegovina", "Sarajevo", "Europe", "Southeast Europe"],
    ["072", "BW", "BWA", "Botswana", "Gaborone", "Africa", "Southern Africa"],
    ["076", "BR", "BRA", "Brazil", "Brasília", "Americas", "South America"],
    ["084", "BZ", "BLZ", "Belize", "Belmopan", "Americas", "Central America"],
    [
        "086",
        "IO",
        "IOT",
        "British Indian Ocean Territory",
        "Diego Garcia",
        "Africa",
        "Eastern Africa",
    ],
    ["090", "SB", "SLB", "Solomon Islands", "Honiara", "Oceania", "Melanesia"],
    ["092", "VG", "VGB", "British Virgin Islands", "Road Town", "Americas", "Caribbean"],
    ["096", "BN", "BRN", "Brunei", "Bandar Seri Begawan", "Asia", "South-Eastern Asia"],
    ["100", "BG", "BGR", "Bulgaria", "Sofia", "Europe", "Southeast Europe"],
    ["104", "MM", "MMR", "Myanmar", "Naypyidaw", "Asia", "South-Eastern Asia"],
    ["108", "BI", "BDI", "Burundi", "Gitega", "Africa", "Eastern Africa"],
    ["112", "BY", "BLR", "Belarus", "Minsk", "Europe", "Eastern Europe"],
    ["116", "KH", "KHM", "Cambodia", "Phnom Penh", "Asia", "South-Eastern Asia"],
    ["120", "CM", "CMR", "Cameroon", "Yaoundé", "Africa", "Middle Africa"],
    ["124", "CA", "CAN", "Canada", "Ottawa", "Americas", "North America"],
    ["132", "CV", "CPV", "Cape Verde", "Praia", "Africa", "Western Africa"],
    ["136", "KY", "CYM", "Cayman Islands", "George Town", "Americas", "Caribbean"],
    ["140", "CF", "CAF", "Central African Republic", "Bangui", "Africa", "Middle Africa"],
    ["144", "LK", "LKA", "Sri Lanka", "Colombo", "Asia", "Southern Asia"],
    ["148", "TD", "TCD", "Chad", "N'Djamena", "Africa", "Middle Africa"],
    ["152", "CL", "CHL", "Chile", "Santiago", "Americas", "South America"],
    ["156", "CN", "CHN", "China", "Beijing", "Asia", "Eastern Asia"],
    ["158", "TW", "TWN", "Taiwan", "Taipei", "Asia", "Eastern Asia"],
    [
        "162",
        "CX",
        "CXR",
        "Christmas Island",
        "Flying Fish Cove",
        "Oceania",
        "Australia and New Zealand",
    ],
    [
        "166",
        "CC",
        "CCK",
        "Cocos (Keeling) Islands",
        "West Island",
        "Oceania",
        "Australia and New Zealand",
    ],
    ["170", "CO", "COL", "Colombia", "Bogotá", "Americas", "South America"],
    ["174", "KM", "COM", "Comoros", "Moroni", "Africa", "Eastern Africa"],
    ["175", "YT", "MYT", "Mayotte", "Mamoudzou", "Africa", "Eastern Africa"],
    ["178", "CG", "COG", "Republic of the Congo", "Brazzaville", "Africa", "Middle Africa"],
    ["180", "CD", "COD", "DR Congo", "Kinshasa", "Africa", "Middle Africa"],
    ["184", "CK", "COK", "Cook Islands", "Avarua", "Oceania", "Polynesia"],
    ["188", "CR", "CRI", "Costa Rica", "San José", "Americas", "Central America"],
    ["191", "HR", "HRV", "Croatia", "Zagreb", "Europe", "Southeast Europe"],
    ["192", "CU", "CUB", "Cuba", "Havana", "Americas", "Caribbean"],
    ["196", "CY", "CYP", "Cyprus", "Nicosia", "Europe", "Southern Europe"],
    ["203", "CZ", "CZE", "Czechia", "Prague", "Europe", "Central Europe"],
    ["204", "BJ", "BEN", "Benin", "Porto-Novo", "Africa", "Western Africa"],
    ["208", "DK", "DNK", "Denmark", "Copenhagen", "Europe", "Northern Europe"],
    ["212", "DM", "DMA", "Dominica", "Roseau", "Americas", "Caribbean"],
    ["214", "DO", "DOM", "Dominican Republic", "Santo Domingo", "Americas", "Caribbean"],
    ["218", "EC", "ECU", "Ecuador", "Quito", "Americas", "South America"],
    ["222", "SV", "SLV", "El Salvador", "San Salvador", "Americas", "Central America"],
    ["226", "GQ", "GNQ", "Equatorial Guinea", "Malabo", "Africa", "Middle Africa"],
    ["231", "ET", "ETH", "Ethiopia", "Addis Ababa", "Africa", "Eastern Africa"],
    ["232", "ER", "ERI", "Eritrea", "Asmara", "Africa", "Eastern Africa"],
    ["233", "EE", "EST", "Estonia", "Tallinn", "Europe", "Northern Europe"],
    ["234", "FO", "FRO", "Faroe Islands", "Tórshavn", "Europe", "Northern Europe"],
    ["238", "FK", "FLK", "Falkland Islands", "Stanley", "Americas", "South America"],
    ["242", "FJ", "FJI", "Fiji", "Suva", "Oceania", "Melanesia"],
    ["246", "FI", "FIN", "Finland", "Helsinki", "Europe", "Northern Europe"],
    ["248", "AX", "ALA", "Åland Islands", "Mariehamn", "Europe", "Northern Europe"],
    ["250", "FR", "FRA", "France", "Paris", "Europe", "Western Europe"],
    ["254", "GF", "GUF", "French Guiana", "Cayenne", "Americas", "South America"],
    ["258", "PF", "PYF", "French Polynesia", "Papeetē", "Oceania", "Polynesia"],
    ["262", "DJ", "DJI", "Djibouti", "Djibouti", "Africa", "Eastern Africa"],
    ["266", "GA", "GAB", "Gabon", "Libreville", "Africa", "Middle Africa"],
    ["268", "GE", "GEO", "Georgia", "Tbilisi", "Asia", "Western Asia"],
    ["270", "GM", "GMB", "Gambia", "Banjul", "Africa", "Western Africa"],
    ["275", "PS", "PSE", "Palestine", "Ramallah", "Asia", "Western Asia"],
    ["276", "DE", "DEU", "Germany", "Berlin", "Europe", "Western Europe"],
    ["288", "GH", "GHA", "Ghana", "Accra", "Africa", "Western Africa"],
    ["292", "GI", "GIB", "Gibraltar", "Gibraltar", "Europe", "Southern Europe"],
    ["296", "KI", "KIR", "Kiribati", "South Tarawa", "Oceania", "Micronesia"],
    ["300", "GR", "GRC", "Greece", "Athens", "Europe", "Southern Europe"],
    ["304", "GL", "GRL", "Greenland", "Nuuk", "Americas", "North America"],
    ["308", "GD", "GRD", "Grenada", "St. George's", "Americas", "Caribbean"],
    ["312", "GP", "GLP", "Guadeloupe", "Basse-Terre", "Americas", "Caribbean"],
    ["316", "GU", "GUM", "Guam", "Hagåtña", "Oceania", "Micronesia"],
    ["320", "GT", "GTM", "Guatemala", "Guatemala City", "Americas", "Central America"],
    ["324", "GN", "GIN", "Guinea", "Conakry", "Africa", "Western Africa"],
    ["328", "GY", "GUY", "Guyana", "Georgetown", "Americas", "South America"],
    ["332", "HT", "HTI", "Haiti", "Port-au-Prince", "Americas", "Caribbean"],
    ["336", "VA", "VAT", "Vatican City", "Vatican City", "Europe", "Southern Europe"],
    ["340", "HN", "HND", "Honduras", "Tegucigalpa", "Americas", "Central America"],
    ["344", "HK", "HKG", "Hong Kong", "City of Victoria", "Asia", "Eastern Asia"],
    ["348", "HU", "HUN", "Hungary", "Budapest", "Europe", "Central Europe"],
    ["352", "IS", "ISL", "Iceland", "Reykjavik", "Europe", "Northern Europe"],
    ["356", "IN", "IND", "India", "New Delhi", "Asia", "Southern Asia"],
    ["360", "ID", "IDN", "Indonesia", "Jakarta", "Asia", "South-Eastern Asia"],
    ["364", "IR", "IRN", "Iran", "Tehran", "Asia", "Southern Asia"],
    ["368", "IQ", "IRQ", "Iraq", "Baghdad", "Asia", "Western Asia"],
    ["372", "IE", "IRL", "Ireland", "Dublin", "Europe", "Northern Europe"],
    ["376", "IL", "ISR", "Israel", "Jerusalem", "Asia", "Western Asia"],
    ["380", "IT", "ITA", "Italy", "Rome", "Europe", "Southern Europe"],
    ["384", "CI", "CIV", "Ivory Coast", "Yamoussoukro", "Africa", "Western Africa"],
    ["388", "JM", "JAM", "Jamaica", "Kingston", "Americas", "Caribbean"],
    ["392", "JP", "JPN", "Japan", "Tokyo", "Asia", "Eastern Asia"],
    ["398", "KZ", "KAZ", "Kazakhstan", "Astana", "Asia", "Central Asia"],
    ["400", "JO", "JOR", "Jordan", "Amman", "Asia", "Western Asia"],
    ["404", "KE", "KEN", "Kenya", "Nairobi", "Africa", "Eastern Africa"],
    ["408", "KP", "PRK", "North Korea", "Pyongyang", "Asia", "Eastern Asia"],
    ["410", "KR", "KOR", "South Korea", "Seoul", "Asia", "Eastern Asia"],
    ["414", "KW", "KWT", "Kuwait", "Kuwait City", "Asia", "Western Asia"],
    ["417", "KG", "KGZ", "Kyrgyzstan", "Bishkek", "Asia", "Central Asia"],
    ["418", "LA", "LAO", "Laos", "Vientiane", "Asia", "South-Eastern Asia"],
    ["422", "LB", "LBN", "Lebanon", "Beirut", "Asia", "Western Asia"],
    ["426", "LS", "LSO", "Lesotho", "Maseru", "Africa", "Southern Africa"],
    ["428", "LV", "LVA", "Latvia", "Riga", "Europe", "Northern Europe"],
    ["430", "LR", "LBR", "Liberia", "Monrovia", "Africa", "Western Africa"],
    ["434", "LY", "LBY", "Libya", "Tripoli", "Africa", "Northern Africa"],
    ["438", "LI", "LIE", "Liechtenstein", "Vaduz", "Europe", "Western Europe"],
    ["440", "LT", "LTU", "Lithuania", "Vilnius", "Europe", "Northern Europe"],
    ["442", "LU", "LUX", "Luxembourg", "Luxembourg", "Europe", "Western Europe"],
    ["446", "MO", "MAC", "Macau", "", "Asia", "Eastern Asia"],
    ["450", "MG", "MDG", "Madagascar", "Antananarivo", "Africa", "Eastern Africa"],
    ["454", "MW", "MWI", "Malawi", "Lilongwe", "Africa", "Eastern Africa"],
    ["458", "MY", "MYS", "Malaysia", "Kuala Lumpur", "Asia", "South-Eastern Asia"],
    ["462", "MV", "MDV", "Maldives", "Malé", "Asia", "Southern Asia"],
    ["466", "ML", "MLI", "Mali", "Bamako", "Africa", "Western Africa"],
    ["470", "MT", "MLT", "Malta", "Valletta", "Europe", "Southern Europe"],
    ["474", "MQ", "MTQ", "Martinique", "Fort-de-France", "Americas", "Caribbean"],
    ["478", "MR", "MRT", "Mauritania", "Nouakchott", "Africa", "Western Africa"],
    ["480", "MU", "MUS", "Mauritius", "Port Louis", "Africa", "Eastern Africa"],
    ["484", "MX", "MEX", "Mexico", "Mexico City", "Americas", "North America"],
    ["492", "MC", "MCO", "Monaco", "Monaco", "Europe", "Western Europe"],
    ["496", "MN", "MNG", "Mongolia", "Ulan Bator", "Asia", "Eastern Asia"],
    ["498", "MD", "MDA", "Moldova", "Chișinău", "Europe", "Eastern Europe"],
    ["499", "ME", "MNE", "Montenegro", "Podgorica", "Europe", "Southeast Europe"],
    ["500", "MS", "MSR", "Montserrat", "Plymouth", "Americas", "Caribbean"],
    ["504", "MA", "MAR", "Morocco", "Rabat", "Africa", "Northern Africa"],
    ["508", "MZ", "MOZ", "Mozambique", "Maputo", "Africa", "Eastern Africa"],
    ["512", "OM", "OMN", "Oman", "Muscat", "Asia", "Western Asia"],
    ["516", "NA", "NAM", "Namibia", "Windhoek", "Africa", "Southern Africa"],
    ["520", "NR", "NRU", "Nauru", "Yaren", "Oceania", "Micronesia"],
    ["524", "NP", "NPL", "Nepal", "Kathmandu", "Asia", "Southern Asia"],
    ["528", "NL", "NLD", "Netherlands", "Amsterdam", "Europe", "Western Europe"],
    ["531", "CW", "CUW", "Curaçao", "Willemstad", "Americas", "Caribbean"],
    ["533", "AW", "ABW", "Aruba", "Oranjestad", "Americas", "Caribbean"],
    ["534", "SX", "SXM", "Sint Maarten", "Philipsburg", "Americas", "Caribbean"],
    ["535", "BQ", "BES", "Caribbean Netherlands", "Kralendijk", "Americas", "Caribbean"],
    ["540", "NC", "NCL", "New Caledonia", "Nouméa", "Oceania", "Melanesia"],
    ["548", "VU", "VUT", "Vanuatu", "Port Vila", "Oceania", "Melanesia"],
    ["554", "NZ", "NZL", "New Zealand", "Wellington", "Oceania", "Australia and New Zealand"],
    ["558", "NI", "NIC", "Nicaragua", "Managua", "Americas", "Central America"],
    ["562", "NE", "NER", "Niger", "Niamey", "Africa", "Western Africa"],
    ["566", "NG", "NGA", "Nigeria", "Abuja", "Africa", "Western Africa"],
    ["570", "NU", "NIU", "Niue", "Alofi", "Oceania", "Polynesia"],
    ["574", "NF", "NFK", "Norfolk Island", "Kingston", "Oceania", "Australia and New Zealand"],
    ["578", "NO", "NOR", "Norway", "Oslo", "Europe", "Northern Europe"],
    ["580", "MP", "MNP", "Northern Mariana Islands", "Saipan", "Oceania", "Micronesia"],
    ["581", "UM", "UMI", "United States Minor Outlying Islands", "", "Americas", "North America"],
    ["583", "FM", "FSM", "Micronesia", "Palikir", "Oceania", "Micronesia"],
    ["584", "MH", "MHL", "Marshall Islands", "Majuro", "Oceania", "Micronesia"],
    ["585", "PW", "PLW", "Palau", "Ngerulmud", "Oceania", "Micronesia"],
    ["586", "PK", "PAK", "Pakistan", "Islamabad", "Asia", "Southern Asia"],
    ["591", "PA", "PAN", "Panama", "Panama City", "Americas", "Central America"],
    ["598", "PG", "PNG", "Papua New Guinea", "Port Moresby", "Oceania", "Melanesia"],
    ["600", "PY", "PRY", "Paraguay", "Asunción", "Americas", "South America"],
    ["604", "PE", "PER", "Peru", "Lima", "Americas", "South America"],
    ["608", "PH", "PHL", "Philippines", "Manila", "Asia", "South-Eastern Asia"],
    ["612", "PN", "PCN", "Pitcairn Islands", "Adamstown", "Oceania", "Polynesia"],
    ["616", "PL", "POL", "Poland", "Warsaw", "Europe", "Central Europe"],
    ["620", "PT", "PRT", "Portugal", "Lisbon", "Europe", "Southern Europe"],
    ["624", "GW", "GNB", "Guinea-Bissau", "Bissau", "Africa", "Western Africa"],
    ["626", "TL", "TLS", "Timor-Leste", "Dili", "Asia", "South-Eastern Asia"],
    ["630", "PR", "PRI", "Puerto Rico", "San Juan", "Americas", "Caribbean"],
    ["634", "QA", "QAT", "Qatar", "Doha", "Asia", "Western Asia"],
    ["638", "RE", "REU", "Réunion", "Saint-Denis", "Africa", "Eastern Africa"],
    ["642", "RO", "ROU", "Romania", "Bucharest", "Europe", "Southeast Europe"],
    ["643", "RU", "RUS", "Russia", "Moscow", "Europe", "Eastern Europe"],
    ["646", "RW", "RWA", "Rwanda", "Kigali", "Africa", "Eastern Africa"],
    ["652", "BL", "BLM", "Saint Barthélemy", "Gustavia", "Americas", "Caribbean"],
    [
        "654",
        "SH",
        "SHN",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Jamestown",
        "Africa",
        "Western Africa",
    ],
    ["659", "KN", "KNA", "Saint Kitts and Nevis", "Basseterre", "Americas", "Caribbean"],
    ["660", "AI", "AIA", "Anguilla", "The Valley", "Americas", "Caribbean"],
    ["662", "LC", "LCA", "Saint Lucia", "Castries", "Americas", "Caribbean"],
    ["663", "MF", "MAF", "Saint Martin", "Marigot", "Americas", "Caribbean"],
    ["666", "PM", "SPM", "Saint Pierre and Miquelon", "Saint-Pierre", "Americas", "North America"],
    ["670", "VC", "VCT", "Saint Vincent and the Grenadines", "Kingstown", "Americas", "Caribbean"],
    ["674", "SM", "SMR", "San Marino", "City of San Marino", "Europe", "Southern Europe"],
    ["678", "ST", "STP", "São Tomé and Príncipe", "São Tomé", "Africa", "Middle Africa"],
    ["682", "SA", "SAU", "Saudi Arabia", "Riyadh", "Asia", "Western Asia"],
    ["686", "SN", "SEN", "Senegal", "Dakar", "Africa", "Western Africa"],
    ["688", "RS", "SRB", "Serbia", "Belgrade", "Europe", "Southeast Europe"],
    ["690", "SC", "SYC", "Seychelles", "Victoria", "Africa", "Eastern Africa"],
    ["694", "SL", "SLE", "Sierra Leone", "Freetown", "Africa", "Western Africa"],
    ["702", "SG", "SGP", "Singapore", "Singapore", "Asia", "South-Eastern Asia"],
    ["703", "SK", "SVK", "Slovakia", "Bratislava", "Europe", "Central Europe"],
    ["704", "VN", "VNM", "Vietnam", "Hanoi", "Asia", "South-Eastern Asia"],
    ["705", "SI", "SVN", "Slovenia", "Ljubljana", "Europe", "Central Europe"],
    ["706", "SO", "SOM", "Somalia", "Mogadishu", "Africa", "Eastern Africa"],
    ["710", "ZA", "ZAF", "South Africa", "Pretoria", "Africa", "Southern Africa"],
    ["716", "ZW", "ZWE", "Zimbabwe", "Harare", "Africa", "Eastern Africa"],
    ["724", "ES", "ESP", "Spain", "Madrid", "Europe", "Southern Europe"],
    ["728", "SS", "SSD", "South Sudan", "Juba", "Africa", "Middle Africa"],
    ["729", "SD", "SDN", "Sudan", "Khartoum", "Africa", "Northern Africa"],
    ["732", "EH", "ESH", "Western Sahara", "El Aaiún", "Africa", "Northern Africa"],
    ["740", "SR", "SUR", "Suriname", "Paramaribo", "Americas", "South America"],
    ["744", "SJ", "SJM", "Svalbard and Jan Mayen", "Longyearbyen", "Europe", "Northern Europe"],
    ["748", "SZ", "SWZ", "Eswatini", "Lobamba", "Africa", "Southern Africa"],
    ["752", "SE", "SWE", "Sweden", "Stockholm", "Europe", "Northern Europe"],
    ["756", "CH", "CHE", "Switzerland", "Bern", "Europe", "Western Europe"],
    ["760", "SY", "SYR", "Syria", "Damascus", "Asia", "Western Asia"],
    ["762", "TJ", "TJK", "Tajikistan", "Dushanbe", "Asia", "Central Asia"],
    ["764", "TH", "THA", "Thailand", "Bangkok", "Asia", "South-Eastern Asia"],
    ["768", "TG", "TGO", "Togo", "Lomé", "Africa", "Western Africa"],
    ["772", "TK", "TKL", "Tokelau", "Fakaofo", "Oceania", "Polynesia"],
    ["776", "TO", "TON", "Tonga", "Nuku'alofa", "Oceania", "Polynesia"],
    ["780", "TT", "TTO", "Trinidad and Tobago", "Port of Spain", "Americas", "Caribbean"],
    ["784", "AE", "ARE", "United Arab Emirates", "Abu Dhabi", "Asia", "Western Asia"],
    ["788", "TN", "TUN", "Tunisia", "Tunis", "Africa", "Northern Africa"],
    ["792", "TR", "TUR", "Türkiye", "Ankara", "Asia", "Western Asia"],
    ["795", "TM", "TKM", "Turkmenistan", "Ashgabat", "Asia", "Central Asia"],
    ["796", "TC", "TCA", "Turks and Caicos Islands", "Cockburn Town", "Americas", "Caribbean"],
    ["798", "TV", "TUV", "Tuvalu", "Funafuti", "Oceania", "Polynesia"],
    ["800", "UG", "UGA", "Uganda", "Kampala", "Africa", "Eastern Africa"],
    ["804", "UA", "UKR", "Ukraine", "Kyiv", "Europe", "Eastern Europe"],
    ["807", "MK", "MKD", "North Macedonia", "Skopje", "Europe", "Southeast Europe"],
    ["818", "EG", "EGY", "Egypt", "Cairo", "Africa", "Northern Africa"],
    ["826", "GB", "GBR", "United Kingdom", "London", "Europe", "Northern Europe"],
    ["831", "GG", "GGY", "Guernsey", "St. Peter Port", "Europe", "Northern Europe"],
    ["832", "JE", "JEY", "Jersey", "Saint Helier", "Europe", "Northern Europe"],
    ["833", "IM", "IMN", "Isle of Man", "Douglas", "Europe", "Northern Europe"],
    ["834", "TZ", "TZA", "Tanzania", "Dodoma", "Africa", "Eastern Africa"],
    ["840", "US", "USA", "United States", "Washington D.C.", "Americas", "North America"],
    [
        "850",
        "VI",
        "VIR",
        "United States Virgin Islands",
        "Charlotte Amalie",
        "Americas",
        "Caribbean",
    ],
    ["854", "BF", "BFA", "Burkina Faso", "Ouagadougou", "Africa", "Western Africa"],
    ["858", "UY", "URY", "Uruguay", "Montevideo", "Americas", "South America"],
    ["860", "UZ", "UZB", "Uzbekistan", "Tashkent", "Asia", "Central Asia"],
    ["862", "VE", "VEN", "Venezuela", "Caracas", "Americas", "South America"],
    ["876", "WF", "WLF", "Wallis and Futuna", "Mata-Utu", "Oceania", "Polynesia"],
    ["882", "WS", "WSM", "Samoa", "Apia", "Oceania", "Polynesia"],
    ["887", "YE", "YEM", "Yemen", "Sana'a", "Asia", "Western Asia"],
    ["894", "ZM", "ZMB", "Zambia", "Lusaka", "Africa", "Eastern Africa"],
];
